### ISSUE TITLE
OpenTox page to create user accounts does not seem to work.

### ISSUE THREAD

**Issue by dphilip** [KinkyDesign/jaqpot-api#43]
The OpenTox page to create user accounts does not seem to work.
http://www.opentox.org/join_form
This however is still operational:
http://old.opentox.org/join_form

**Comment by AValsamis** [comment]
This is now resolved with https://github.com/KinkyDesign/jaqpot-web/commit/77ff2cfa6ea0430956e738eb8175eeb0a2f868e3
